# protoactor-widget-actor-deployment.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: protoactor-k8s-grains-node1
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.protoActorCluster.subdomain }}
  replicas: 1
  selector:
    matchLabels:
      app: protoactor-k8s-grains-node1
  template:
    metadata:
      labels:
        app: protoactor-k8s-grains-node1
        protoActorMember: "true"
    spec:
      serviceAccountName: protoactor-k8s-grains-serviceaccount
      containers:
      - name: protoactor-k8s-grains-node1
        image: {{ .Values.node1.image }}
        ports:
         - containerPort: 4020
           name: protoactor