apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.protoActorCluster.subdomain }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    protoActorMember: "true"
  ports:
    - name: protoactor-k8s-cluster-port-service
      protocol: TCP
      port: 4020
      targetPort: 4020
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None