# protoactor-widget-actor-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: protoactor-k8s-grains-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: protoactor-k8s-grains-role
subjects:
  - kind: ServiceAccount
    name: protoactor-k8s-grains-serviceaccount